version: "3.8"

services:
  app-tm:
    build:
      context: ./app-tm
      dockerfile: Dockerfile
    container_name: app-tm
    ports:
      - "3005:3005"
    depends_on:
      - monadic-sbd-server

  app-tool:
    build:
      context: ./app-tool
      dockerfile: Dockerfile
    container_name: app-tool
    ports:
      - "3000:3000"
    depends_on:
      - app-tm
      - monadic-sbd-server

  monadic-sbd-server:
    image: public.ecr.aws/b4j5l6c5/europeana/monadic.sbd_server:v1
    container_name: monadic-sbd-server
    ports:
      - "81:80"
    environment:
      - SBD_SERVER_PORT=81
      - NODE_ENV=production